<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Domain\MirajOfIcarus.Domain.csproj" />
    <ProjectReference Include="..\..\..\game-server\libraries\contracts\MirajOfIcarus.Game.Contracts\MirajOfIcarus.Game.Contracts.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
