set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR AMD64)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES MIRAJ_OF_ICARUS_XWIN_ROOT)

set(MIRAJ_OF_ICARUS_WINDOWS_SDK_VERSION "10.0.26100")

if(NOT DEFINED MIRAJ_OF_ICARUS_XWIN_ROOT)
  message(FATAL_ERROR "Pass -DMIRAJ_OF_ICARUS_XWIN_ROOT=/path/to/xwin/splat")
endif()
set(MIRAJ_OF_ICARUS_XWIN_ROOT "${MIRAJ_OF_ICARUS_XWIN_ROOT}" CACHE PATH "xwin splat root")

set(CMAKE_C_COMPILER clang-cl-20)
set(CMAKE_CXX_COMPILER clang-cl-20)
set(CMAKE_LINKER lld-link-20)
set(CMAKE_AR llvm-lib-20)
set(CMAKE_RC_COMPILER llvm-rc-20)
set(CMAKE_MT llvm-mt-20)

set(MIRAJ_OF_ICARUS_TARGET_FLAGS
  "--target=x86_64-pc-windows-msvc /vctoolsdir ${MIRAJ_OF_ICARUS_XWIN_ROOT}/crt /winsdkdir ${MIRAJ_OF_ICARUS_XWIN_ROOT}/sdk")
set(MIRAJ_OF_ICARUS_COMPAT_INCLUDE "${CMAKE_CURRENT_LIST_DIR}/windows-compat")
set(CMAKE_C_FLAGS_INIT "${MIRAJ_OF_ICARUS_TARGET_FLAGS} /I${MIRAJ_OF_ICARUS_COMPAT_INCLUDE}")
set(CMAKE_CXX_FLAGS_INIT "${MIRAJ_OF_ICARUS_TARGET_FLAGS} /I${MIRAJ_OF_ICARUS_COMPAT_INCLUDE}")
set(MIRAJ_OF_ICARUS_LINK_FLAGS
  "/libpath:${MIRAJ_OF_ICARUS_XWIN_ROOT}/crt/lib/x64 /libpath:${MIRAJ_OF_ICARUS_XWIN_ROOT}/sdk/Lib/${MIRAJ_OF_ICARUS_WINDOWS_SDK_VERSION}/ucrt/x64 /libpath:${MIRAJ_OF_ICARUS_XWIN_ROOT}/sdk/Lib/${MIRAJ_OF_ICARUS_WINDOWS_SDK_VERSION}/um/x64")
set(CMAKE_EXE_LINKER_FLAGS_INIT "${MIRAJ_OF_ICARUS_LINK_FLAGS}")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "${MIRAJ_OF_ICARUS_LINK_FLAGS}")
set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")

set(CMAKE_FIND_ROOT_PATH "${MIRAJ_OF_ICARUS_XWIN_ROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
