export const routes = {
  home: "/",
  login: "/entrar",
  register: "/criar-conta",
  client: "/cliente",
  panel: "/painel",
  game: "/o-jogo",
  gameAbout: "/o-jogo#sobre",
  skills: "/o-jogo#skills",
  community: "/comunidade",
  reconstruction: "/#reconstrucao",
  realms: "/reinos",
  download: "/download",
  trade: "/trade",
  shop: "/shop",
  classes: "/#classes",
  prestige: "/#prestigio",
} as const;
