#pragma once

#define IDI_MIRAJ_OF_ICARUS 101
#define IDR_LAUNCHER_BACKGROUND 201
#define IDR_LAUNCHER_MARK 202
#define IDR_LAUNCHER_FRAME 203
#define IDR_BUTTON_DEFAULT 204
#define IDR_BUTTON_FOCUSED 205
#define IDR_BUTTON_PRESSED 206
#define IDR_BUTTON_DISABLED 207
#define IDR_WINDOW_CONTROLS 208
#define IDR_MIRAJ_DISPLAY_FONT 209
